name: Doxygen Action

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "doxygen.cfg" 
        working-directory: "./docs" # default is .
   
    - name: Copy custom elements 
      run: |
         chmod +x ./.github/workflows/doxygen_custom.sh 
         ./.github/workflows/doxygen_custom.sh 

         sass style.scss:style.css --style compressed
         mkdir -p ./docs/html/customjs
         mkdir -p ./

 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
